version: '3'
services:
  nginxBABCNfrontend:
    build: ""
    image: business-assistant-bcn-frontend
    container_name: business-assistant-bcn-frontend
    restart: "no"
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/uad-docker.conf > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
